version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule
  open-pull-requests-limit: 10
  labels:
  - "\U0001F4E6 dependencies"
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - "\U0001F4E6 dependencies"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: 
  labels:
  - "\U0001F4E6 dependencies"
